[package]
name = "actix-app-template"
version = "0.1.0"
authors = ["Hunter Mellema <mellemahp@gmail.com>, Connor Johnstone <>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"